"""add_bonus_features

Revision ID: 1787c1e2953e
Revises: 2c21829a4502
Create Date: 2026-06-07 18:32:37.095202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1787c1e2953e'
down_revision: Union[str, None] = '2c21829a4502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('enrollments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('uq_user_course'), 'enrollments', type_='unique')
    op.create_index('uq_user_course', 'enrollments', ['user_id', 'course_id'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_course', table_name='enrollments', postgresql_where='deleted_at IS NULL')
    op.create_unique_constraint(op.f('uq_user_course'), 'enrollments', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('enrollments', 'deleted_at')
    op.drop_column('courses', 'deleted_at')
    op.drop_table('enrollment_audit_logs')
    # ### end Alembic commands ###
